package com.zerotrust.authservice.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * SecurityAlert is a JPA entity representing an alert generated by the system.
 * <p>
 * Alerts are created when something looks suspicious (high risk score, denied access, unknown location, etc.).
 * They are stored in the {@code security_alerts} table and returned to the UI as notifications.
 */
@Entity
@Table(name = "security_alerts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SecurityAlert {
    /** Database identifier for the alert. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Email of the user related to the alert. */
    private String userEmail;

    /** Alert category (example: "HIGH_RISK", "SUSPICIOUS_IP", "UNKNOWN_LOCATION"). */
    private String type;

    /** Human-readable message explaining what triggered the alert. */
    private String message;

    /** Resource involved in the event that triggered the alert. */
    private String resource;

    /** Action involved in the event (example: "LOGIN", "DELETE"). */
    private String action;

    /** Risk score associated with the event. */
    private Integer riskScore;

    /** Date/time when the alert was created (server time). */
    private LocalDateTime createdAt;
}

