# Name of the Spring Boot application (used internally for logs, etc.)
spring.application.name=auth-service

# Port on which the backend will run (http://localhost:8081)
server.port=8081


# ================= DATABASE CONFIG =================

# JDBC URL to connect to PostgreSQL (running locally via Docker)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/zero_trust_cloud

# Username used by Spring Boot to connect to the database
spring.datasource.username=ztc_user

# Password for the database user
spring.datasource.password=ztc_password

# PostgreSQL driver (tells Java how to talk to PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver


# ================= JPA / HIBERNATE =================

# Automatically create/update database tables based on your entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true

