spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/zero_trust_cloud
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
