package com.zerotrust.authservice.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * SecurityAlertResponse is a DTO (Data Transfer Object) returned by the API when the client
 * fetches security alerts.
 * <p>
 * A security alert is a message generated by the system to highlight suspicious or important events
 * (for example: many failed logins, access denied to a sensitive resource, etc.).
 * <p>
 * This DTO is read-only: it is used for responses, not for creating alerts.
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SecurityAlertResponse {

    /** Unique identifier of the alert. */
    private Long id;

    /** Email of the user related to the alert. */
    private String userEmail;

    /** Alert type/category (example: "LOGIN_ATTEMPT", "DATA_ACCESS"). */
    private String type;

    /** Human-readable description of what happened. */
    private String message;

    /** Resource or subsystem impacted (example: "Auth Service", "/api/admin"). */
    private String resource;

    /** Action that triggered the alert (example: "LOGIN", "READ"). */
    private String action;

    /** Risk level associated with the alert (higher usually means more dangerous). */
    private Integer riskScore;

    /** Date/time when the alert was created (server time). */
    private LocalDateTime createdAt;
}
